[package]
name = "bevy_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
bevy_client_server_events = "0.6.0"
bevy_flycam = "0.12.0"
lazy_static = "1.4.0"
serde = "1.0.193"

